konnect/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('konnectapp/', include('konnectapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/konnectapp/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

konnectapp/urls.py
from django.urls import path

from . import views
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.index, name='index'),
    path('question/add/', views.QuestionCreate.as_view(), name='question-add'),
    path('questions/', views.QuestionListView.as_view(), name='questions'),
    path('answers/', views.AnswerListView.as_view(), name='answers'),
    path('question/<int:pk>', views.QuestionDetailView.as_view(), name='question-detail'),
    path('question/<int:pk>/answer/', views.AnswerCreate.as_view(), name='answer-add'),
    path('answer/<int:pk>/delete/', views.DeleteAnswer.as_view(), name='delete-answer'),
    path('question/<int:pk>/update/', views.UpdateQuestion.as_view(), name='question-update'),
    path('question/<int:pk>/delete/', views.DeleteQuestion.as_view(), name='question-delete'),
    path('answer/<int:pk>/update/', views.UpdateAnswer.as_view(), name='answer-update'),
    path('answer/<int:pk>/comment/', views.CommentCreate.as_view(), name='comment-add'),
    path('comment/<int:pk>/delete/', views.CommentDelete.as_view(), name='comment-delete'),
    path('answer/upvote/<int:pk>', views.UpvoteCreate.as_view(), name='answer-upvote'),
    path('search/', views.SearchView.as_view(), name='search'),


    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('author/add/', views.AuthorCreate.as_view(), name='author-add'),
    path('author/<int:pk>/', views.AuthorUpdate.as_view(), name='author-update'),
    path('about/', views.about, name='about'),
    path('overview/', views.overview, name='overview'),
]
urlpatterns += staticfiles_urlpatterns()

konnectapp/models.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
from django.db.models import Q
from django.core.validators import MinValueValidator, MaxValueValidator

class Author(models.Model):

    #Model to store author details
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=70, blank=True)
    date_created = models.DateField(null=True, default=timezone.now())
    credits = models.IntegerField(default=0)
    year = models.DateField(null=True, default=timezone.now())


    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])
        # return reverse('author-detail', kwargs={'pk': self.pk})
        # another way of doing this

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.user.username}'


class AuthorAdmin(admin.ModelAdmin):
    list_display = ('user', 'email', 'date_created', 'credits')


class Comment(models.Model):

    """Model representing a question."""
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    answer = models.ForeignKey('Answer', on_delete=models.SET_NULL, null=True)
    comment_text = models.TextField(max_length=1000, help_text='Enter your comment...')
    date_created = models.DateField(default=timezone.now())
    date_updated = models.DateField(default=timezone.now())

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.comment_text}'


class CommentAdmin(admin.ModelAdmin):
    list_display = ('comment_text', 'author', 'date_created')
    list_filter = ('date_created', 'author')


class Answer(models.Model):

    """Model representing a question."""
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    question = models.ForeignKey('Question', on_delete=models.SET_NULL, null=True)
    answer_text = models.TextField(max_length=2000, help_text='Write your answer here...')
    date_created = models.DateField(null=True, default=timezone.now())
    date_updated = models.DateField(null=True, default=timezone.now())
    upvote = models.IntegerField(default=0)

    downvote = models.IntegerField(default=0)
    views = models.IntegerField(default=0)

    def __str__(self):
        """String for representing the Model object."""
        return f'Que: {self.question.question_text[:50]}.. Ans: {self.answer_text[:50]}..'



class AnswerAdmin(admin.ModelAdmin):
    list_display = (
        'question', 'answer_text', 'author', 'date_created', 'upvote','views')
    list_filter = ('date_created', 'author', 'upvote', 'views')
    fieldsets = (
        (None, {
            'fields': ('author','question', 'answer_text')
        }),
        ('Dates', {
            'fields': ('date_created', 'date_updated')
        }),
        ('Actions', {
            'fields': ('upvote', 'views')
        }),
    )


class PostQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (Q(question_title__icontains=query) |
                         Q(question_text__icontains=query)|
                         Q(slug__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model,using=self._db)
    def search(self,query=None):
        return self.get_queryset().search(query=query)




class Question(models.Model):

    """Model representing a question."""
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    question_title = models.TextField(max_length=300, help_text='Enter the question title')
    question_text = models.TextField(max_length=1000, help_text='Your question in brief')
    date_created = models.DateField(null=True, default=timezone.now())
    date_updated = models.DateField(null=True, default=timezone.now())
    time_created = models.TimeField(null=True, default=timezone.now())
    slug         = models.SlugField(blank=True, unique=False)
    objects = PostManager()


    tags=TaggableManager()

    def create_tags(self, tags):
        tags = tags.strip()
        tag_list = tags.split(' ')
        for tag in tag_list:
            if tag:
                t, created = Tag.objects.get_or_create(tag=tag.lower(), question=self)

    def get_tags(self):
        return Tag.objects.filter(question=self)
    def get_absolute_url(self):
        """Returns the url to access a particular question and its answer."""
        return reverse('question-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.question_text}'


class QuestionAdmin(admin.ModelAdmin):
    list_display = ('question_text', 'author', 'date_created')
    list_filter = ('date_created', 'author')

konnectapp/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from .models import Question


class PostForm(forms.ModelForm):




    class Meta:
        model = Question
        fields = ['question_title', 'date_created', 'tags']

konnectapp/views.py
from django.contrib.auth.hashers import PBKDF2PasswordHasher
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect, render, get_object_or_404

from itertools import chain
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView

from konnectapp.models import Answer, Author, Comment, Question
from taggit.models import Tag
from django.template.defaultfilters import slugify
from .forms import PostForm
from django.db import IntegrityError




class UpdateAnswer(LoginRequiredMixin, UpdateView):
    model = Answer
    fields = ['answer_text']
    template_name = 'konnectapp/answer_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answer_id = self.kwargs['pk']
        answer = Answer.objects.get(id=answer_id)
        self.pk = answer.question.id
        context['answer_text'] = answer.answer_text
        return context

    def get_success_url(self):
        return (reverse('question-detail', kwargs={'pk': self.object.question.id}))

class DeleteAnswer(LoginRequiredMixin, DeleteView):
    model = Answer
    template_name = 'konnectapp/answer_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answer_id = self.kwargs['pk']
        answer = Answer.objects.get(id=answer_id).delete()
        #self.pk = answer.question.id

        return context

    def get_success_url(self):
        return (reverse('question-detail', kwargs={'pk': self.object.question.id}))

class UpdateQuestion(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['question_text','question_title']
    success_url = reverse_lazy('questions')
    template_name = 'konnectapp/question_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_id = self.kwargs['pk']
        question = Question.objects.get(id=question_id)
        context['question_text'] = question.question_text
        context['question_title'] = question.question_title
        return context
class DeleteQuestion(LoginRequiredMixin, DeleteView):
        model = Question
        success_message = "Deleted Successfully"
        success_url = reverse_lazy('questions')
        template_name = 'konnectapp/question_delete.html'
        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)

            question_id = self.kwargs['pk']
            question = Question.objects.get(id=question_id).delete()


            #context['question_text'] = question.question_text.delete()
            #context['question_title'] = question.question_title.delete()
            return context


class SearchView(ListView):
    template_name = 'views.html'
    paginate_by = 20
    count = 0

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['count'] = self.count or 0
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', None)

        if query is not None:
            blog_results = Question.objects.search(query)


            # combine querysets
            queryset_chain = chain(
                    blog_results,

            )
            qs = sorted(queryset_chain,
                        key=lambda instance: instance.pk,
                        reverse=True)
            self.count = len(qs) # since qs is actually a list
            return qs
        return Question.objects.none() # just an empty queryset as default




class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['author', 'answer', 'comment_text']

    def get(self, request, *args, **kwargs):
        a_id = self.kwargs['pk']
        return render(request, 'konnectapp/comment_form.html', {"a_id": a_id})

    def post(self, request, *args, **kwargs):
        comment_text = request.POST.get('comment_text')
        params = self.kwargs['pk']
        author = Author.objects.get(user=self.request.user)
        answer = Answer.objects.get(id=params)
        Comment.objects.create(
            author=author, answer=answer, comment_text=comment_text)
        response = redirect(
            reverse('question-detail', kwargs={'pk': answer.question.id}))
        return response

class CommentDelete(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'konnectapp/comment_delete.html'



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        a_id = self.kwargs['pk']
        comment = Comment.objects.get(id=a_id).delete()

        #context['comment_text'] =Comment.comment_text.delete()
        #context['question_title'] = question.question_title.delete()
        return context

class UpvoteCreate(LoginRequiredMixin, CreateView):
    model = Answer
    fields = ['answer_text', 'id', 'upvote']

    def post(self, request, *args, **kwargs):
        answer_id = self.kwargs['pk']
        answer = Answer.objects.filter(id=answer_id).first()

        answer.upvote +=1

        answer.save()

        response = redirect(
            reverse('question-detail', kwargs={'pk': answer.question.id}))
        return response

    """def vote_foo_question(request, **kwargs, value):


        answer_id = self.kwargs['pk']
        answer = get_object_or_404(Answer, pk=answer_id)
        vote = Answer.objects.filter(user_id=answer_id).first()



        vote.value = value
        vote.save()
        question.update_votes()
        question.save()

        return redirect('questions:show', question_id)"""






class QuestionCreate(LoginRequiredMixin, CreateView):
    model = Question
    fields = ['question_title','question_text', 'tags']



    def get(self, request, *args, **kwargs):
        return render(request, 'konnectapp/question_form.html')

    def post(self, request, *args, **kwargs):
        question_title = request.POST.get('question_title')
        question_text = request.POST.get('question_text')


        question = Question.objects.create(author=Author.objects.get(user=self.request.user),question_text=question_text,question_title=question_title)



        response = redirect('/konnectapp/questions')
        return response
    def tagged(request, slug):
        tags = get_object_or_404(Tags, slug=slug)
        common_tags = Question.tags.most_common()[:4]
        posts = Question.objects.filter(tags=tag)
        context = {
            'tag':tag,
            'common_tags':common_tags,
            'question':question,
            }
        response = redirect('/konnectapp/questions')
        return response


class AnswerCreate(LoginRequiredMixin, CreateView):
    model = Answer
    fields = ['answer_text']

    def get(self, request, *args, **kwargs):
        q_id = self.kwargs['pk']
        return render(request, 'konnectapp/answer_form.html', {"q_id": q_id})

    def post(self, request, *args, **kwargs):
        answer_text = request.POST.get('answer_text')
        answer = Answer.objects.create(author=Author.objects.get(
            user=self.request.user), question=Question.objects.get(
                id=self.kwargs['pk']), answer_text=answer_text)
        response = redirect(reverse('question-detail', kwargs={'pk': answer.question.id}))
        return response


class AuthorCreate(CreateView):
    model = Author
    fields = ['email']

    def get(self, request, *args, **kwargs):
        return render(request, 'konnectapp/author_form.html')

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        year = request.POST.get('year')
        email = request.POST.get('email')

        if password1 == password2:
            hasher = PBKDF2PasswordHasher()
            password = hasher.encode(
                password=password1, salt='salt', iterations=150000)
        try:
            user = User.objects.create(username=username, password=password)
            Author.objects.create(user=user, email=email,year=year )
        except IntegrityError:
            return render(request, 'konnectapp/userexists.html')
            #return response
            raise ValidationError(_("This username has already existed."))
        else:
            response = redirect('/accounts/login')
            return response




class AuthorUpdate(UpdateView):
    model = Author
    fields = ['email']


class AuthorDelete(DeleteView):
    model = Author
    fields = ['user']
    fields = ['email']
    fields = ['credits']
    success_url = reverse_lazy('questions')


class AuthorDetailView(generic.DetailView):
    """Generic class-based detail view for an Author."""
    model = Author


class QuestionDetailView(generic.DetailView):
    """Generic class-based detail view for a Question."""
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_id = self.kwargs['pk']
        question = Question.objects.get(id=question_id)
        answer_list = Answer.objects.filter(question=question)
        comment_dictionary = {
                ans.id: Comment.objects.filter(answer=ans) for ans in answer_list
            }


        context['answer_list'] = answer_list
        context['answer_url'] = '/konnectapp/question/'+str(question_id)+'/answer/'
        context['upvote_url'] = '/konnectapp/answer/upvote/'
        context['downvote_url'] = '/konnectapp/answer/downvote/'
        context['comment_dictionary'] = comment_dictionary
        return context




class AnswerListView(generic.ListView):
    model = Answer

konnectapp/templates/konnectapp/answer_delete.html
{% extends "base_generic.html" %}
{% block content %}


   <h3>Your Answer has been Deleted</h3>
  <h5><a   href="/konnectapp/questions/"  </a>Back</h5>
{% endblock %}

konnectapp/templates/konnectapp/answer_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action='/konnectapp/question/{{q_id}}/answer/' method="POST">
    {% csrf_token %}
    <label for="answer_text">Write your answer</label>
    <br>
    <br>
    <textarea name="answer_text" id="answer_text" cols="80" rows="10" required></textarea>

    <br><br>
    <button type="submit" class="btn btn-primary">Answer</button>
</form>

{% endblock %}

konnectapp/templates/konnectapp/answer_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>answer List</h1>
  {% if answer_list %}
  <ul>
      
    {% for answer in answer_list %}
      <div class="row text-info">
          &nbsp; {{ answer.question.question_text }} 
      </div>
          <hr></hr>
        <div class="row text-dark">
          {{ answer.answer_text }}</a> 
        </div>
        <br>
        <br>
        <div class="row text-success">
            <div class="col"></div>
            <div class="col-6"></div>
            <div class="col">
                by <a href="{{ answer.author.get_absolute_url }}">{{answer.author}} </a> 
                (on {{answer.date_updated}}) 
            </div>
        </div>
       
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no answers in the library.</p>
  {% endif %}       
{% endblock %}

konnectapp/templates/konnectapp/answer_update_form.html
{% extends "base_generic.html" %}

{% block content %}

    <form method="POST">
        <div class="form-group">
            {% csrf_token %}
        </div>

        <div class="form-group">
            <label for="id_answer_text">Answer text:</label>
            <textarea class="form-control" name="answer_text" cols="40" rows="10" maxlength="1000" required id="id_answer_text">
                    {{answer_text}}
            </textarea>
            

        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>

{% endblock %}

konnectapp/templates/konnectapp/author_detail.html
{% extends "base_generic.html" %}

{% block content %}


<h2>User Details</h2>
<hr>
<ul>

        <li><strong>User: </strong> {{ author.user.username }}</li>
        <li><strong>Email Id: </strong> {{ author.email }}</li>
        <li><strong>Graduating/Graduated Year: </strong> {{ author.year }}</li>
        <li><strong>Account Created on: </strong> {{ author.date_created }}</li>

</ul>
{% endblock %}

konnectapp/templates/konnectapp/author_form.html
{% extends "base_generic.html" %}

{% block content %}
    <br>
    <form action='/konnectapp/author/add/' method='post'>
        {% csrf_token %}
        <div class="form-group">
        <label for="id_username">Username:</label>
        <input type="text" name="username"  class="form-control" autofocus required id="id_username">

        </div>
        <div class="form-group"></div>
        <label for="email">Your Email:</label>
        <input type="email" name="email" id="email"  class="form-control" aria-describedby="emailHelp" placeholder="Enter email" required>
        <br>
        <label for="year">Graduating/Graduated Year:</label>
        <input type="date" id="datemax" name="year" class="form-control" max="2045-12-31" required>
        <br>
        <div class="form-group">
            <label for="id_password1">Password:</label>
            <input type="password" name="password1" minlength="8" required id="id_password1" class="form-control" placeholder="Enter Password">
            <span class="helptext">
            <ul>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can&#39;t be entirely numeric.</li>
            </ul>
            </span>
        </div>
        <div class="form-group">
            <label for="id_password2">Password confirmation:</label>
            <input type="password" name="password2" minlength="8" required id="id_password2" class="form-control" placeholder="Confirm Password">
            <span class="helptext">Enter the same password as before, for verification.</span>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>

    </form>

{% endblock %}

konnectapp/templates/konnectapp/comment_delete.html
{% extends "base_generic.html" %}
{% block content %}


   <h3>Your Comment has been Deleted</h3>
  <h5><a   href="/konnectapp/questions"  </a>Back</h5>
{% endblock %}

konnectapp/templates/konnectapp/comment_form.html
{% extends "base_generic.html" %}


{% block content %}
<form action='/konnectapp/answer/{{a_id}}/comment/' method="post">

    {% csrf_token %}
    <label for="comment_text">Write your comment: </label>
    <br>
    <br>
    <textarea name="comment_text" id="comment_text" cols="80" rows="8" required></textarea>

    <br><br>
    <button type="submit" class="btn btn-primary">Comment</button>
</form>
{% endblock %}

konnectapp/templates/konnectapp/question_delete.html
{% extends "base_generic.html" %}
{% block content %}


   <h3>Your Question has been Deleted</h3>
  <h5><a   href="/konnectapp/questions"  </a>Back</h5>
{% endblock %}

konnectapp/templates/konnectapp/question_detail.html
{% extends "base_generic.html" %}

{% block content %}

<style>
  .boxed {
  border: 1px solid White ;
}
</style>
 <div style="margin-left: 5px;" class="text-info">
     <h3 style="border:3px solid #99ddff;background-color:#f2f2f2;border-radius: 5px;" > {{ question.question_title }} : </h3>

 </div>
 <div style="margin-left: 45px;" class="boxed">
   {{ question.question_text }}


 </div>
 <hr>




   <div class="text-success">
     <div class="row">
         <div class="col">
           <form action = "{{answer_url}}" method = "GET" >
             <input type = "hidden" name = "q_id" value = {{q_id}} />
             <input type ="submit"  class="btn btn-success" role="button" value="Answer this question &#128161;"   >
           </form>
         </div>
         <div class="col-7"></div>
         <div class="col">
           <strong>User:</strong> <a href="{{ question.author.get_absolute_url }}">{{ question.author }}</a>
           <br>
           <strong>Created On:</strong> {{ question.date_created }}
         </div>
     </div>

  <div style="margin-left:20px;margin-top:10px; margin-right: 10px;">

    {% if answer_list %}
    <ul>
        <h4>All Answers</h4>
      {% for answer in answer_list %}
          <br>
          <div class="card">
            <div class="card-body">
              {% comment %} <h5 class="card-title">Special title treatment</h5> {% endcomment %}
              <p class="card-text">
                <div class="row text-dark">
            {{ answer.answer_text }}
          </div>
          <br>
          <br>
          <div class="row text-success">

            <!-- upvote form -->
              <div class="col">
                <form action="{{upvote_url}}{{answer.id}}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="Upvote" class="btn btn-primary">
                  <span class="text-dark">{{ answer.upvote }} &#128316;</span>
                </form>
              </div>




            <!-- comment form -->
            <div class="col">
                <form action="/konnectapp/answer/{{answer.id}}/comment/" method="GET">
                  {% csrf_token %}
                  <input type="submit" value="Comment" class="btn btn-primary">
                </form>
            </div>

            {% comment %} update answer {% endcomment %}
            <div class="col-4">
            {% if user.is_authenticated %}
              {% if  user.get_username  ==  answer.author.user.username  %}
                  <a href="/konnectapp/answer/{{answer.id}}/update/" class="btn btn-primary">Update Answer</a>
                  <a href="/konnectapp/answer/{{answer.id}}/delete/" class="btn btn-primary">Delete Answer</a>
              {% endif %}
            {% endif %}
            </div>
            <div class="col-3">
                  by <a href="{{ answer.author.get_absolute_url }}">{{answer.author}} </a>
                  (on {{answer.date_updated}})
            </div>

              </p>
              {% comment %} <a style="padding: 3px;" class="btn-success " href="/konnectapp/question/{{question.id}}/update/">Update Question</a> {% endcomment %}
              {% comment %} <a style="padding: 3px;" class="btn-success" href="/konnectapp/question/">Delete Question</a> {% endcomment %}
            </div>
          </div>
 </div>

 <div style="margin-left: 50px;">
        <br>

        <ul class="list-group">

          {% for key, comment in comment_dictionary.items %}
            {% if key == answer.id %}
              {% if comment %}
                {% for comm in comment %}


                    <li class="list-group-item disabled">{{ comm }}</li>
                    <div class="col-7">
                          comment by <a style="color:green;" href="{{ answer.author.get_absolute_url }}">{{comm.author}} </a>
                          (on {{comm.date_updated}})



                    </div>
                    <div class="col-4">
                    {% if user.is_authenticated %}
                      {% if  user.get_username  ==  comm.author.user.username  %}
                          <a href="/konnectapp/comment/{{comm.id}}/delete/" class="btn btn-secondary btn-sm">Delete Comment</a>
                      {% endif %}
                    {% endif %}
                    </div>



                {% endfor %}
              {% endif %}
            {% endif %}
          {% endfor %}
        <ul>
        </div>

      {% endfor %}

    </div>
    </ul>
    {% else %}

    <div class="text-danger">
        There are no answers for this question.
    </div>

    {% endif %}

  </div>
{% endblock %}

konnectapp/templates/konnectapp/question_form.html
{% extends "base_generic.html" %}


{% block content %}

<form action='/konnectapp/question/add/' method="post">

    {% csrf_token %}
    <label for="question_title">Question Title: </label>

    <br>

    <textarea style="white-space: normal;"  name="question_title" id="question_title" cols="50" rows="1" required></textarea>
    <br>
    <label for="question_text">Question Text: </label>
    <br>
    <textarea name="question_text" id="question_text" cols="50" rows="10" required></textarea>



    <br>
    <button type="submit" class="btn btn-primary">Ask</button>
</form>
{% endblock %}

konnectapp/templates/konnectapp/question_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Question List &#128196;</h1>
  {% if question_list %}
  <ul reversed class="list-group"  >
    {% for question in question_list %}
      <li style="padding: 4px; margin: 3px; list-style: none; text-decoration: none;" class="list-group-item list-group-item-action list-group-item-dark">
        <a style="text-decoration: none; color: black" href="{{ question.get_absolute_url }}?ordering=time_created && date_created">{{ question.question_title }}</a>
        &nbsp; &nbsp; &nbsp;
        By
        <a style="text-decoration: bold; color: blue;" href="{{ question.author.get_absolute_url }}"> <b>{{question.author}}</b> </a>
        (on {{question.date_updated}})

        {% if user.is_authenticated %}
            {% if  user.get_username  ==  question.author.user.username  %}
                <a style="padding: 3px; text-decoration: none;" class="btn btn-primary" href="/konnectapp/question/{{question.id}}/update/">Update Question</a>
                <a style="padding: 3px; text-decoration: none;" class="btn btn-primary" href="/konnectapp/question/{{question.id}}/delete/">Delete Question</a>
            {% endif %}
        {% endif %}
      </li>
    {% endfor %}

  </ul>
  {% else %}
    <p>There are no questions posted yet.</p>
  {% endif %}
{% endblock %}

konnectapp/templates/konnectapp/question_update_form.html
{% extends "base_generic.html" %}


{% block content %}
<style>


p.b {
  white-space: normal;
}

</style>
<form method="POST">

    <div class="form-group">
        {% csrf_token %}
    </div>

    <div class="b">
        <label for="id_question_title">Question text:</label>
        <br>
        <textarea   name="question_title" cols="50" rows="1" maxlength="300" required id="id_question_title">
                {{question_title}}
        </textarea>
        <br>
        <label for="id_question_text">Question text:</label>
        <br>
        <textarea  name="question_text" cols="50" rows="10" maxlength="1000"  required id="id_question_text">
                {{question_text}}
        </textarea>
        <br>
        <span class="helptext">Enter your question in brief</span>
    </div>


    <button type="submit" class="btn btn-primary">Update</button>
</form>


{% endblock %}

konnectapp/templates/konnectapp/userexists.html
{% extends "base_generic.html" %}

{% block content %}

        <h3>Username Already exists. Try with a different Username</h3>
        <h5><a style=" color: blue"  href="/konnectapp/author/add"  </a>Back</h5>



{% endblock %}